=== Bhargav09/bhargavgangadhara/iPCentralProjectImageResponse.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by Selvaraj Aran (Cisco Systems) -->
<!-- Copyright (c) 2006-2010 by Cisco Systems, Inc. All rights reserved. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Action">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="IPCentralProjectImage"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClientName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClientRequestId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RequesterUserId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ReleaseNumberID">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ReleaseNumber">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IPCentralProjectID">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="OSTypeID" type="xs:unsignedInt"/>
	<xs:element name="MDFSoftwareTypeID" type="xs:unsignedInt"/>
	<xs:element name="SoftwareTypeName">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ImageId" type="xs:unsignedInt"/>
	<xs:element name="ImageName" type="xs:string"/>
	<xs:element name="ImageDescription" type="xs:string"/>
	<xs:element name="MD5Cheksum" type="xs:string"/>
	<xs:element name="CCOPostStatus">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CCOPostedDated">
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AdmFlag">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CreatedBy">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CreatedDate">
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LastUpdatedDate">
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ImageResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ResponseCode" nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ResponseType" default="Info" nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="32"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ResponseDescription" default="Request is successfully processed in SPRIT." nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ResponseComments" nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Timestamp" type="xs:dateTime" nillable="false"/>
				<xs:element name="UpdatedBy" fixed="SPRIT" nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="8"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Data" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Start"/>
							<xs:element ref="Limit"/>
							<xs:element ref="TotalCount"/>
							<xs:element ref="PageCount"/>
							<xs:element name="Release" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="ReleaseNumberID"/>
										<xs:element ref="ReleaseNumber"/>
										<xs:element ref="IPCentralProjectID" minOccurs="0"/>
										<xs:element ref="OSTypeID"/>
										<xs:element ref="MDFSoftwareTypeID"/>
										<xs:element ref="SoftwareTypeName"/>
										<xs:element name="Image" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="ImageId"/>
													<xs:element ref="ImageName"/>
													<xs:element ref="ImageDescription" minOccurs="0"/>
													<xs:element ref="MD5Cheksum" minOccurs="0"/>
													<xs:element ref="CCOPostStatus" minOccurs="0"/>
													<xs:element ref="CCOPostedDated" minOccurs="0"/>
													<xs:element ref="AdmFlag"/>
													<xs:element ref="CreatedBy"/>
													<xs:element ref="CreatedDate"/>
													<xs:element ref="LastUpdatedDate"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SpritInternal">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SpritRequestId" default="1" nillable="false">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:minInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Start">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Limit">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TotalCount">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PageCount">
		<xs:simpleType>
			<xs:restriction base="xs:integer"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SPRITImageResponse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ClientName"/>
				<xs:element ref="ClientRequestId"/>
				<xs:element ref="Action"/>
				<xs:element ref="ImageResponse"/>
				<xs:element ref="SpritInternal"/>
			</xs:sequence>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="1.0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bhargav09/bhargavgangadhara/iPCentralProjectImageResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 (http://www.altova.com)-->
<SPRITImageResponse version="1.0" xsi:noNamespaceSchemaLocation="iPCentralProjectImageResponse.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ClientName>a</ClientName>
	<ClientRequestId>a</ClientRequestId>
	<Action>IPCentralProjectImage</Action>
	<ImageResponse>
		<ResponseCode>0</ResponseCode>
		<ResponseType>Info</ResponseType>
		<ResponseDescription>Request is successfully processed in SPRIT.</ResponseDescription>
		<ResponseComments></ResponseComments>
		<Timestamp>2001-12-17T09:30:47.0Z</Timestamp>
		<UpdatedBy>SPRIT</UpdatedBy>
	</ImageResponse>
	<SpritInternal>
		<SpritRequestId>28791</SpritRequestId>
	</SpritInternal>
	<Data>
	<Start> 1 </Start>
	<Limit> 3 </Limit>
	<TotalCount>1 </TotalCount>
	<PageCount> 2 </PageCount>
	<Release>
		<ReleaseNumberID>23517</ReleaseNumberID>
		<ReleaseNumber>12.2(33)SXI2</ReleaseNumber>
		<IPCentralProjectID>ipcentralid101</IPCentralProjectID>
		<OSTypeID>1</OSTypeID>
		<MDFSoftwareTypeID>280805680</MDFSoftwareTypeID>
		<SoftwareTypeName>IOS Software</SoftwareTypeName>
		<Image>
			<ImageId>1458735</ImageId>
			<ImageName>s3223-adventerprisek9_wan-vz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>0419a3543061db9f2a0b5c29a901d65b</MD5Cheksum>
			<CCOPostStatus>Repost Success</CCOPostStatus>
			<CCOPostedDated>2009-09-23T01:09:07</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>vwadhera</CreatedBy>
			<CreatedDate>2009-05-11T10:05:12</CreatedDate>
			<LastUpdatedDate>2009-09-24T02:09:52</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1458734</ImageId>
			<ImageName>s3223-adventerprisek9_wan-mz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>3906a86c164d4f8e100e6bd2187ad62c</MD5Cheksum>
			<CCOPostStatus>Repost Success</CCOPostStatus>
			<CCOPostedDated>2009-09-23T01:09:05</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>vwadhera</CreatedBy>
			<CreatedDate>2009-05-11T10:05:12</CreatedDate>
			<LastUpdatedDate>2009-09-24T02:09:52</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1458731</ImageId>
			<ImageName>s3223-adventerprise_wan-vz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>2e7281ef0335264cbd260591a258d925</MD5Cheksum>
			<CCOPostStatus>Repost Success</CCOPostStatus>
			<CCOPostedDated>2009-09-23T01:09:08</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>vwadhera</CreatedBy>
			<CreatedDate>2009-05-11T10:05:12</CreatedDate>
			<LastUpdatedDate>2009-09-24T02:09:52</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1458730</ImageId>
			<ImageName>s3223-adventerprise_wan-mz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>d3077eef995e64fc493c7c00adbd197f</MD5Cheksum>
			<CCOPostStatus>Repost Success</CCOPostStatus>
			<CCOPostedDated>2009-09-23T01:09:07</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>vwadhera</CreatedBy>
			<CreatedDate>2009-05-11T10:05:12</CreatedDate>
			<LastUpdatedDate>2009-09-24T02:09:52</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1458729</ImageId>
			<ImageName>c6500-fpd-pkg</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>1ec250ff59202279734f98d6337a6c42</MD5Cheksum>
			<CCOPostStatus>Repost Success</CCOPostStatus>
			<CCOPostedDated>2009-09-23T01:09:08</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>vwadhera</CreatedBy>
			<CreatedDate>2009-05-11T10:05:12</CreatedDate>
			<LastUpdatedDate>2009-09-23T01:09:08</LastUpdatedDate>
		</Image>
	</Release>
	<Release>
		<ReleaseNumberID>27249</ReleaseNumberID>
		<ReleaseNumber>12.2(33)SXI3</ReleaseNumber>
		<IPCentralProjectID>ipcentralid101</IPCentralProjectID>
		<OSTypeID>1</OSTypeID>
		<MDFSoftwareTypeID>280805680</MDFSoftwareTypeID>
		<SoftwareTypeName>IOS Software</SoftwareTypeName>
		<Image>
			<ImageId>1474959</ImageId>
			<ImageName>s3223-adventerprisek9_wan-vz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>daa3bf2e7b94b8bfea4e1936e8a58976</MD5Cheksum>
			<CCOPostStatus>Post Success</CCOPostStatus>
			<CCOPostedDated>2009-11-04T02:11:06</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>jgbajabi</CreatedBy>
			<CreatedDate>2009-07-02T12:07:02</CreatedDate>
			<LastUpdatedDate>2009-11-04T02:11:06</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1474958</ImageId>
			<ImageName>s3223-adventerprisek9_wan-mz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>636cd05008653d524913d1cfa54d33db</MD5Cheksum>
			<CCOPostStatus>Post Success</CCOPostStatus>
			<CCOPostedDated>2009-11-04T02:11:05</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>jgbajabi</CreatedBy>
			<CreatedDate>2009-07-02T12:07:01</CreatedDate>
			<LastUpdatedDate>2009-11-04T02:11:05</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1474955</ImageId>
			<ImageName>s3223-adventerprise_wan-vz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>b1338c777abe8fdcbfb648998d33e408</MD5Cheksum>
			<CCOPostStatus>Post Success</CCOPostStatus>
			<CCOPostedDated>2009-11-04T02:11:05</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>jgbajabi</CreatedBy>
			<CreatedDate>2009-07-02T12:07:01</CreatedDate>
			<LastUpdatedDate>2009-11-04T02:11:05</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1474954</ImageId>
			<ImageName>s3223-adventerprise_wan-mz</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>a74533a21f27561978fc92ef174f3155</MD5Cheksum>
			<CCOPostStatus>Post Success</CCOPostStatus>
			<CCOPostedDated>2009-11-04T02:11:02</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>jgbajabi</CreatedBy>
			<CreatedDate>2009-07-02T12:07:01</CreatedDate>
			<LastUpdatedDate>2009-11-04T02:11:02</LastUpdatedDate>
		</Image>
		<Image>
			<ImageId>1474953</ImageId>
			<ImageName>c6500-fpd-pkg</ImageName>
			<ImageDescription>ENTERPRISE</ImageDescription>
			<MD5Cheksum>2f198062eac5b2f667efd293b236a379</MD5Cheksum>
			<CCOPostStatus>Post Success</CCOPostStatus>
			<CCOPostedDated>2009-11-04T02:11:03</CCOPostedDated>
			<AdmFlag>V</AdmFlag>
			<CreatedBy>jgbajabi</CreatedBy>
			<CreatedDate>2009-07-02T12:07:00</CreatedDate>
			<LastUpdatedDate>2009-11-04T02:11:03</LastUpdatedDate>
		</Image>
	</Release>
	</Data>
</SPRITImageResponse>
